routes:
  /signup/: members\signup
  /signin/: members\signin
  /account/: members\account

collections:
  /:
    permalink: /{slug}/
    template: index
    filter: 'tag:-note'    
  /notes/:
    permalink: /{slug}/
    template: tag-inline-content
    filter: 'tag:note'  
    data: tag.note

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/